import {
  AlertTriangle,
  ArrowRight,
  Bus,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Ticket,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  User2Icon,
  X,
} from "lucide-react";
import DriverIcon from "./driver-icon";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  bus: Bus,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  driver: DriverIcon,
  post: FileText,
  page: File,
  ticket: Ticket,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
};
